# Generated by Django 3.0.8 on 2022-05-13 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('useremail', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('userrollno', models.CharField(max_length=50)),
                ('usercontactto', models.CharField(max_length=50)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='extra_info_of_bbsbec_user',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('intrest', models.CharField(default='', max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('crollno', models.CharField(max_length=50)),
                ('urollno', models.CharField(max_length=50)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogcomment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffpanel.learn_topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
