# Generated by Django 3.0.8 on 2022-05-13 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('keyword', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(choices=[('Gurjeet S Grewal', 'Gurjeet S Grewal')], default='Gurjeet S Grewal', max_length=20)),
                ('pdffile_source', models.CharField(choices=[('Google', 'Google'), ('Media', 'Media')], default='Google', max_length=20)),
                ('pdffile', models.FileField(blank=True, upload_to='blog/posts/pdfs')),
                ('pdflink', models.URLField(blank=True, max_length=300)),
                ('shortdesc', models.CharField(default='', max_length=150)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('category', models.CharField(choices=[('Hacking', 'Hacking'), ('C++', 'C++')], default='Hacking', max_length=20)),
                ('image', models.ImageField(upload_to='blog/posts')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Postcomment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
