"""
Django settings for studywithus project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.contrib.messages import constants as messages
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's1rfkao6%q5rnz&9-8wxv!pn=j90ew(+)=*4$4cb&wvjbwq85p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "app.apps.AppConfig",
    "staffpanel.apps.StaffpanelConfig",
    "utils.apps.UtilsConfig",
    "exam.apps.ExamConfig",
    'mathfilters',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'blog.apps.BlogConfig',
    'robots',
    'image_optimizer',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studywithus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studywithus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'OPTIONS': {
#             'database':'learndjango',
#             'read_default_file': '/auth/mysqlauth.cnf',
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'deqbo3id80d25o',                      
#         'USER': 'qalpifvdedyunu',
#         'PASSWORD': 'eeeed8b9f9daccafbf4e096c7ba6fc986a1f5956b08a3f506efe6451383bd3a9',
#         'HOST': 'ec2-54-86-224-85.compute-1.amazonaws.com',
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     # os.path.join(BASE_DIR, "static"),
#     '/var/www/static/',
# ]
STATIC_ROOT = os.path.join(BASE_DIR, "static")
# MEDIA_ROOT = '/var/www/leanwithus/media'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'
# Custom messages tag
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}
# smtp settings
EMAIL_FROM_USER = 'admin@sampurnanagar.com'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_HOST_USER = 'admin@sampurnanagar.com'
EMAIL_HOST_PASSWORD = 'Mom143@#'
EMAIL_USE_SSL = True
EMAIL_PORT = 465

# robots txt setting
SITE_ID = 2
ROBOTS_USE_SCHEME_IN_HOST = True
ROBOTS_CACHE_TIMEOUT = 60*60*24
ROBOTS_USE_SITEMAP = True
ROBOTS_SITEMAP_URLS = [
    'http://127.0.0.1/sitemap.xml',
]
OPTIMIZED_IMAGE_METHOD = 'pillow'