# Generated by Django 3.0.8 on 2022-05-13 14:35

from django.db import migrations, models
import django.utils.timezone
import staffpanel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_chapter',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('chapter', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('topicname', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='additional_info',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('user', models.CharField(default='lucifer', max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='extra_info_of_professor',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('step2verification', models.CharField(default='False', max_length=50)),
                ('subjects', models.CharField(max_length=500)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='learn_topic',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('topicname', models.CharField(blank=True, max_length=100, null=True)),
                ('videosource', models.CharField(blank=True, max_length=10, null=True)),
                ('videolink', models.URLField(blank=True, null=True)),
                ('topiccontent', models.TextField(blank=True, null=True)),
                ('prismdisplay', staffpanel.fields.NonStrippingTextField(blank=True, default='', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatetimestamp', models.DateTimeField(auto_now=True)),
                ('announcement', models.CharField(default='Any Course related announcements will be posted here', max_length=100)),
            ],
        ),
    ]
